name: safehaven-security
services:
- name: safehaven-security
  source_dir: /
  github:
    repo: mayoalexander/multi-tenant-regional-landingpage-ui
    branch: main
    deploy_on_push: true
  build_command: npm run build
  run_command: npm start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-0.5gb
  http_port: 3000
  routes:
  - path: /